version: '3.1'

networks:
  app-network:
    name: app-network
    driver:
      bridge

services:
  rabbitmq:
    container_name: rabbitmq
    image: masstransit/rabbitmq:3.13
    ports:
      - 5672:5672
      - 15672:15672
      - 15692:15692
    networks:
      - app-network

  mongodb:
    container_name: mongodb
    image: mongo:7.0.0
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    networks:
      - app-network

  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.45.6
    ports:
      - 9090:9090
    volumes:
      - "./conf/prometheus.yml:/etc/prometheus/prometheus.yml"
    command: 
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    networks:
      - app-network

  grafana:
    container_name: grafana
    image: grafana/grafana:9.5.20
    ports:
      - 3500:3000
    networks:
      - app-network

  orchestrator:
    container_name: orchestrator
    build: ./Orchestrator/
    ports:
      - 5103:8080
    depends_on:
      - mongodb
      - rabbitmq
    restart: always
    environment:
      - ConnectionStrings:Mongodb=mongodb://root:root@mongodb:27017/nerdburguer-orchestrator?authSource=admin
      - RabbitMQ:Host=rabbitmq
      - RabbitMQ:User=guest
      - RabbitMQ:Pass=guest
    networks:
      - app-network

  kitchen:
    container_name: kitchen
    build: ./Kitchen/
    ports:
      - 8088:8088
    environment:
      - PORT=8088
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=guest
      - RABBITMQ_PASS=guest
      - RABBITMQ_HOST=rabbitmq
      - MONGODB_CONNECTION_STRING=mongodb://root:root@mongodb:27017/nerdburguer-kitchen?authSource=admin
    depends_on:
      - mongodb
      - rabbitmq
    restart: always
    networks:
      - app-network

  delivery:
    container_name: delivery
    build: ./Delivery/
    ports:
      - 9099:9099
    environment:
      - PORT=9099
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=guest
      - RABBITMQ_PASS=guest
      - RABBITMQ_HOST=rabbitmq
      - MONGODB_CONNECTION_STRING=mongodb://root:root@mongodb:27017/nerdburguer-delivery?authSource=admin
    depends_on:
      - mongodb
      - rabbitmq
    restart: always
    networks:
      - app-network

  front:
    container_name: front
    build: ./Front/
    depends_on:
      - orchestrator
    ports:
      - 3300:80
    restart: always
    networks:
      - app-network
