# CREATE - ORDER
POST http://localhost:5103/api/v1/orders
content-type: application/json

{
  "customerName": "Tiago lima",
  "productName": "X-Salada Duplo",
  "quantity": "1"
}

###

# COOKING - ORDER
POST http://localhost:5103/api/v1/kitchen/orders/96562140-31b6-4cdf-a00c-9f4aa238c12c
content-type: application/json


###

# DELIVERY - ORDER
POST http://localhost:5103/api/v1/delivery/orders/96562140-31b6-4cdf-a00c-9f4aa238c12c
content-type: application/json

###

# FINISH - ORDER
POST http://localhost:5103/api/v1/orders/96562140-31b6-4cdf-a00c-9f4aa238c12c/finish
content-type: application/json
