# ORDER to KITCHEN
GET http://localhost:5103/api/v1/kitchen/orders
content-type: application/json

###

# ORDER - CREATED
POST http://localhost:5103/api/v1/orders
content-type: application/json

{
  "customerName": "Tiago lima",
  "productName": "X-Salada Duplo",
  "quantity": "1"
}

###

# ORDER to KITCHEN
POST http://localhost:5103/api/v1/kitchen/orders/1e08dd28-c7e9-47bc-870c-907c7115e43c
content-type: application/json


###

# ORDER to DELIVERY
POST http://localhost:5103/api/v1/delivery/orders/1e08dd28-c7e9-47bc-870c-907c7115e43c
content-type: application/json

###

# ORDER to FINISH
POST http://localhost:5103/api/v1/orders/1e08dd28-c7e9-47bc-870c-907c7115e43c/finish
content-type: application/json
